diffdrive_arduino_node:
  ros__parameters:
    use_pid: true
    turn_gain: 0.8

    left_wheel.kp: 2.0
    left_wheel.ki: 0.1
    left_wheel.kd: 0.01

    right_wheel.kp: 2.0
    right_wheel.ki: 0.1
    right_wheel.kd: 0.01